### ISSUE TITLE
illegal Windows filename characters when creating a new log file 

### ISSUE THREAD

**Issue by Panospan** [contentful/contentful-merge#505]
I am facing ENOENT error, caused by illegal Windows filename characters on src/engine/logger/write-log.ts

```
new Date().toISOString()
'2023-11-05T14:56:17.530Z'
```
 this fixed my issue:
 from
 
 ```
path.join(process.cwd(), `log-${logger.getType()}-${new Date().toISOString()}.log`)
 ```
 
 to:
 ```
 path.join(process.cwd(), `log-${logger.getType()}-${new Date().toISOString().replaceAll(":",".")}.log`)
 ```

**Comment by marcolink** [comment]
Hi @Panospan,
thanks for reporting this - a fix is on its way: https://github.com/contentful/contentful-merge/pull/527
