### ISSUE TITLE
An authorisation issue occurred when running contentful-merge create

### ISSUE THREAD

**Issue by carloscuba** [contentful/contentful-merge#859]
When trying to run the `create` command, I'm getting the following error:

```
Start changeset creation for development => pre-release 🎬
❯ Creating a Changeset
  ✔ Check content model [0.3s]
  ❯ Entries
    ✔ Reading the source environment "development" [0.1s]
    ✔ Reading the target environment "pre-release" [0.1s]
    ✔ Counting number of entries changes between environments [0.0s]
    ✖ Fetching full payload for 565 entries to be compared
    ◼ Checking for diverged content types
    ◼ Fetching full payload for added entries

Changeset could not be created 💔
An authorisation issue occurred. Please make sure the API key you provided has access to both environments.

📖 /opt/project/log-create-changeset-1712153443729.log
```

I've already checked the CDA Token I'm using has access to both environments (`development` and `pre-release`), and I have even granted it with access to all the environments, but the issue persists.

Please, let me know if there's anything else I can try to fix the problem.
Thanks in advance!

**Comment by GregerGu** [comment]
I'm experiencing the same issue. Created a separate key for this with full access to all environments. Seems like this might be a rate limit issue rather than auth

**Comment by GregerGu** [comment]
@carloscuba I resolved this with the help of support. If your content model in quite big, it can result in a too big request size. It returns the auth error message as a generic error. To fix this, set request size manually using the `--request-batch-size` flag. It is 1000 by default, set it to 500 or lower and see if it works then

**Comment by admapop** [comment]
@GregerGu Can confirm this solves the error for me. In my case I had to go even lower on the batch size. The error message is deceiving.

**Comment by veu** [comment]
https://github.com/contentful/contentful-merge/pull/907
